using Newtonsoft.Json;
using RestSharp;
using System.Security.Principal;

namespace OrgGoalsBCAndNetsuiteCrud.Models
{
    #region Netsuite:Get Vendor
    public class NetsuiteVendorModel
    {
        public List<NetsuiteVendorLink> links { get; set; }
        public int count { get; set; }
        public bool hasMore { get; set; }
        public List<NetsuiteVendorItem> items { get; set; }
        public int offset { get; set; }
        public int totalResults { get; set; }
    }

    public class NetsuiteVendorLink
    {
        public string rel { get; set; }
        public string href { get; set; }
    }

    public class NetsuiteVendorItem
    {
        public object[] links { get; set; }
        public string altname { get; set; }
        public string balance { get; set; }
        public string balanceprimary { get; set; }
        public string currency { get; set; }
        public string datecreated { get; set; }
        public string duplicate { get; set; }
        public string emailpreference { get; set; }
        public string emailtransactions { get; set; }
        public string entityid { get; set; }
        public string entitytitle { get; set; }
        public string faxtransactions { get; set; }
        public string giveaccess { get; set; }
        public string globalsubscriptionstatus { get; set; }
        public string id { get; set; }
        public string isautogeneratedrepresentingentity { get; set; }
        public string isinactive { get; set; }
        public string isjobresourcevend { get; set; }
        public string isperson { get; set; }
        public string lastmodifieddate { get; set; }
        public string prepaymentbalance { get; set; }
        public string printtransactions { get; set; }
        public string subsidiary { get; set; }
        public string subsidiaryedition { get; set; }
        public string symbol { get; set; }
        public string unbilledorders { get; set; }
        public string unbilledordersprimary { get; set; }
        public string companyname { get; set; }
        public string custentity_11724_pay_bank_fees { get; set; }
        public string custentity_2663_eft_file_format { get; set; }
        public string custentity_2663_payment_method { get; set; }
        public string entitynumber { get; set; }
        public string legalname { get; set; }
        public string predconfidence { get; set; }
        public string predicteddays { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string creditlimit { get; set; }
        public string custentity_2663_email_address_notif { get; set; }
        public string defaultbillingaddress { get; set; }
        public string defaultshippingaddress { get; set; }
        public string email { get; set; }
        public string expenseaccount { get; set; }
        public string payablesaccount { get; set; }
        public string state { get; set; }
        public string terms { get; set; }
        public string zip { get; set; }
        public string category { get; set; }
        public string accountnumber { get; set; }
        public string externalid { get; set; }
        public string phone { get; set; }
        public string url { get; set; }
        public string custentity_9572_vendor_entitybank_format { get; set; }
        public string custentity_9572_vendor_entitybank_sub { get; set; }
        public string custentity_tax_reg_no { get; set; }
        public string defaultvendorpaymentaccount { get; set; }
        public string representingsubsidiary { get; set; }
        public string altphone { get; set; }
        public string contact { get; set; }
        public string contactlist { get; set; }
        public string fax { get; set; }
        public string incoterm { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string salutation { get; set; }
    }
    #endregion


    #region Sample request
    //   {
    //    "internalId":"1840",
    //    "firstName": "AK",
    //    "middleName": "Vendor",
    //    "lastName": "D",
    //    "companyName": "Satva Vendor JJJ",
    //    "subsidiary": {
    //        "internalId": "1"
    //    }
    //}
    #endregion
}
